name: Playwright Tests
on:
  push:
    branches: [ main, master, testbranch ]
  pull_request:
    branches: [ main, master, testbranch ]
jobs:
  Playwright_Behave:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with: 
        python-version: 3.13.7
        
    - name: Install dependencies
      run: |
       pip install --upgrade pip
       pip install -r requirements.txt
       pip install playwright
       playwright install
       pip install behave
       npm install -D @cucumber/cucumber@latest
       npm i -D @cucumber/cucumber@latest
       pip install behave-html-formatter

    - name: Run Behave
      run: behave -f html -o reports/test_report.html







 
